### ISSUE TITLE
Problema con Visualizza Preferiti

### ISSUE THREAD

**Issue by PorfirioTramontana** [GiovanniRoso/CulTrip#3]
La lista dei Preferiti non si riempie dopo Aggiungi, nonostante il login col mio account Google sembra essere andato a buon fine.

Problema riscontrato solo sul dispositivo.

Messaggio di errore:

2019-06-06 11:01:11.480 17037-17037/com.example.applicazioneesame E/AuthUI: A sign-in error occurred.
    com.firebase.ui.auth.FirebaseUiException: Code: 10, message: 10: 
        at com.firebase.ui.auth.data.remote.GoogleSignInHandler.onActivityResult(GoogleSignInHandler.java:110)
        at com.firebase.ui.auth.ui.idp.SingleSignInActivity.onActivityResult(SingleSignInActivity.java:128)
        at android.app.Activity.dispatchActivityResult(Activity.java:7276)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4350)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4397)
        at android.app.ActivityThread.-wrap19(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:169)
        at android.app.ActivityThread.main(ActivityThread.java:6578)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by PorfirioTramontana** [comment]
Ho visto che ora l'applicazione si chiude se non riesce l'autenticazione.
Sfortunatamente, siccome non ha mai riconosciuto la mia autenticazione, ora non posso più provare le altre funzionalità.
